/*
  `mpdf-006` Phase 6: the picture of the window the landing page shows, and the
  screenshots of the landing page its author approves.

    bun web/hero.mjs            web/hero-light.png and web/hero-dark.png
    bun web/hero.mjs --shots    _shots/landing-<engine>-<width>-<scheme>.png, eight

  **The picture is the window, captured, not drawn.** A drawing would drift from
  the window; this is regenerated by one command. It opens the image example in
  the assembled site's own app page, in Chromium at 1280 × 800 and device scale
  factor 2, once per `colorScheme`, and waits until the session is `current` and
  the first page's canvas holds a pixel that is not white — the page drawn, not
  just laid out. The two files are committed, since the landing page must render
  with no build step.

  **`--shots` spawns one child per engine**, as `web/check.mjs`'s header records:
  a second browser launch in one process hangs. Each child writes the landing
  page's viewport at 1280 × 900 and 390 × 844, light and dark. They are what
  gate 3 puts in front of the author, and are never committed.

  It assembles the site itself, as `web/check.mjs` does, so `web/pkg/` must be
  built first — `cd web && wasm-pack build --target web --release`.
*/

import { chromium, webkit } from 'playwright'
import { spawnSync } from 'node:child_process'
import { mkdirSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { serve } from './serve.mjs'

const ROOT = resolve(import.meta.dir, '..')
const SITE = join(ROOT, '_site')
const SHOTS = join(ROOT, '_shots')
const argv = process.argv.slice(2)
const SCHEMES = ['light', 'dark']
const LOAD = 90_000

function die(message) {
  console.error(`hero: ${message}`)
  process.exit(2)
}

function assemble() {
  const built = spawnSync('bash', [join(ROOT, 'web/assemble.sh')], { encoding: 'utf8' })
  if (built.status !== 0) die(`web/assemble.sh failed:\n${built.stderr}`)
}

function wait(ms) {
  return new Promise((done) => setTimeout(done, ms))
}

/** `web/check.mjs`'s `polled`, for one state: an async predicate cannot go to `waitForFunction`. */
async function current(page) {
  const deadline = Date.now() + LOAD
  for (;;) {
    const now = await page.evaluate(() => window.__TAURI__.core.invoke('status'))
    if (now.state === 'current') return
    if (Date.now() > deadline) die(`timed out in state ${now.state}`)
    await wait(50)
  }
}

/** True once the first page's canvas holds a pixel that is not white. */
function drawn() {
  const canvas = document.querySelector('#pages canvas')
  if (canvas === null || canvas.width === 0 || canvas.height === 0) return false
  const { data } = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height)
  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] !== 0 && (data[i] < 250 || data[i + 1] < 250 || data[i + 2] < 250)) return true
  }
  return false
}

async function capture(base) {
  const browser = await chromium.launch({ headless: true })
  for (const colorScheme of SCHEMES) {
    const context = await browser.newContext({
      viewport: { width: 1280, height: 800 },
      deviceScaleFactor: 2,
      colorScheme
    })
    const page = await context.newPage()
    await page.goto(`${base}/app/#example=caption-image`, { waitUntil: 'load' })
    await current(page)
    await page.waitForFunction(drawn, null, { timeout: LOAD, polling: 100 })
    const path = join(ROOT, `web/hero-${colorScheme}.png`)
    await page.screenshot({ path })
    console.log(`wrote ${path}`)
    await context.close()
  }
  await browser.close()
}

async function shots(base, engine) {
  mkdirSync(SHOTS, { recursive: true })
  const browser = await (engine === 'webkit' ? webkit : chromium).launch({ headless: true })
  for (const [width, height] of [[1280, 900], [390, 844]]) {
    for (const colorScheme of SCHEMES) {
      const context = await browser.newContext({ viewport: { width, height }, colorScheme })
      const page = await context.newPage()
      await page.goto(`${base}/`, { waitUntil: 'networkidle' })
      await page.evaluate(() => document.fonts.ready)
      const path = join(SHOTS, `landing-${engine}-${width}-${colorScheme}.png`)
      await page.screenshot({ path })
      console.log(`wrote ${path}`)
      await context.close()
    }
  }
  await browser.close()
}

/* -------------------------------------------------------------------- main */

if (argv.includes('--shots') && !argv.includes('--engine')) {
  assemble()
  for (const engine of ['chromium', 'webkit']) {
    const child = spawnSync('bun', [import.meta.path, '--shots', '--engine', engine], { stdio: 'inherit' })
    if (child.status !== 0) die(`the ${engine} child exited ${child.status}`)
  }
  process.exit(0)
}

if (!argv.includes('--engine')) assemble()
const { url: base, server } = await serve(SITE)
if (argv.includes('--shots')) await shots(base, argv[argv.indexOf('--engine') + 1])
else await capture(base)
server.close()
