/*
  `mpdf-006` Phases 6 and 7: every picture the landing page shows, and the
  screenshots of the landing page its author approves.

    bun web/hero.mjs            web/hero-light.png, web/hero-dark.png, and
                                web/pages/NAME.png for each ok example, with
                                web/pages/pages.json; prints each row's size
    bun web/hero.mjs --shots    _shots/landing-<engine>-…png, fourteen

  **The picture is the window, captured, not drawn.** A drawing would drift from
  the window; this is regenerated by one command. It opens the image example in
  the assembled site's own app page, in Chromium at 1280 × 800 and device scale
  factor 2, once per `colorScheme`, and waits until the session is `current` and
  the first page's canvas holds a pixel that is not white — the page drawn, not
  just laid out. The two files are committed, since the landing page must render
  with no build step.

  **Each row's picture is the page the window holds** — Phase 7. For each `ok`
  example it opens `app/#example=NAME`, waits for `current`, takes the PDF the
  window holds (`current_pdf`, the bytes `web/check.mjs` clause (c) compares with
  the CLI's), and renders its one page with the window's own vendored pdf.js at
  3 canvas pixels per PDF point, whatever the device scale factor. It is
  cropped to the ink — every pixel with a channel under 250 — padded 36 px and
  clamped to the page. It dies on an example that makes more than one page.
  `web/pages/pages.json` maps each name to the SHA-256 of the PDF its picture
  came from, which is what clause (c) holds the pictures to; the printed
  `width`/`height`, `Math.round(px × 4 / 9)`, are written into `web/index.html`
  by hand, and clause (a) holds them to the pixels.

  **`--shots` spawns one child per engine**, as `web/check.mjs`'s header records:
  a second browser launch in one process hangs. Each child writes the landing
  page's viewport at 1280 × 900 and 390 × 844, light and dark, and then the
  whole page three ways: 1280 light and 390 light with every `<details>`
  closed, and 1280 dark with every one open. A full-page capture does not
  scroll, so before each it scrolls every row's picture into view and waits for
  all nine: a lazy one below the fold would be captured as an empty slot. They
  are what the phases' gates put in front of the author, and are never
  committed.

  It assembles the site itself, as `web/check.mjs` does, so `web/pkg/` must be
  built first — `cd web && wasm-pack build --target web --release`.
*/

import { chromium, webkit } from 'playwright'
import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { serve } from './serve.mjs'

const ROOT = resolve(import.meta.dir, '..')
const SITE = join(ROOT, '_site')
const SHOTS = join(ROOT, '_shots')
const PAGES = join(ROOT, 'web/pages')
const argv = process.argv.slice(2)
const SCHEMES = ['light', 'dark']
const LOAD = 90_000

/** The `ok` examples, in page order, by the element shape `web/check.mjs` reads. */
const OK = [...readFileSync(join(ROOT, 'web/index.html'), 'utf8').matchAll(
  /<script type="text\/markdown" data-example="([^"]+)" data-expect="ok">/g
)].map(([, name]) => name)

function die(message) {
  console.error(`hero: ${message}`)
  process.exit(2)
}

function assemble() {
  const built = spawnSync('bash', [join(ROOT, 'web/assemble.sh')], { encoding: 'utf8' })
  if (built.status !== 0) die(`web/assemble.sh failed:\n${built.stderr}`)
}

function wait(ms) {
  return new Promise((done) => setTimeout(done, ms))
}

/** `web/check.mjs`'s `polled`, for one state: an async predicate cannot go to `waitForFunction`. */
async function current(page) {
  const deadline = Date.now() + LOAD
  for (;;) {
    const now = await page.evaluate(() => window.__TAURI__.core.invoke('status'))
    if (now.state === 'current') return
    if (Date.now() > deadline) die(`timed out in state ${now.state}`)
    await wait(50)
  }
}

/** True once the first page's canvas holds a pixel that is not white. */
function drawn() {
  const canvas = document.querySelector('#pages canvas')
  if (canvas === null || canvas.width === 0 || canvas.height === 0) return false
  const { data } = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height)
  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] !== 0 && (data[i] < 250 || data[i + 1] < 250 || data[i + 2] < 250)) return true
  }
  return false
}

async function capture(browser, base) {
  for (const colorScheme of SCHEMES) {
    const context = await browser.newContext({
      viewport: { width: 1280, height: 800 },
      deviceScaleFactor: 2,
      colorScheme
    })
    const page = await context.newPage()
    await page.goto(`${base}/app/#example=caption-image`, { waitUntil: 'load' })
    await current(page)
    await page.waitForFunction(drawn, null, { timeout: LOAD, polling: 100 })
    const path = join(ROOT, `web/hero-${colorScheme}.png`)
    await page.screenshot({ path })
    console.log(`wrote ${path}`)
    await context.close()
  }
}

/**
 * Run in the app page: the PDF the window holds, its one page rendered at 3
 * canvas pixels per point and cropped to the ink. Answers a string on refusal.
 */
async function rendered() {
  const bytes = new Uint8Array(await window.__TAURI__.core.invoke('current_pdf'))
  const kept = Array.from(bytes)
  // The window imported this same URL, so its worker is already configured.
  const pdfjs = await import('/app/pdfjs/pdf.min.mjs')
  const pdf = await pdfjs.getDocument({ data: bytes.slice() }).promise
  if (pdf.numPages !== 1) return `makes ${pdf.numPages} pages, not one`
  const first = await pdf.getPage(1)
  const viewport = first.getViewport({ scale: 3 })
  const canvas = document.createElement('canvas')
  canvas.width = Math.floor(viewport.width)
  canvas.height = Math.floor(viewport.height)
  const context = canvas.getContext('2d')
  await first.render({ canvasContext: context, viewport }).promise

  const { width, height } = canvas
  const { data } = context.getImageData(0, 0, width, height)
  let [left, top, right, bottom] = [width, height, -1, -1]
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 4
      if (data[i] < 250 || data[i + 1] < 250 || data[i + 2] < 250) {
        if (x < left) left = x
        if (x > right) right = x
        if (y < top) top = y
        if (y > bottom) bottom = y
      }
    }
  }
  if (right < 0) return 'sets a page with no ink'
  const PAD = 36
  left = Math.max(0, left - PAD)
  top = Math.max(0, top - PAD)
  right = Math.min(width - 1, right + PAD)
  bottom = Math.min(height - 1, bottom + PAD)
  const crop = document.createElement('canvas')
  crop.width = right - left + 1
  crop.height = bottom - top + 1
  crop.getContext('2d').drawImage(canvas, left, top, crop.width, crop.height, 0, 0, crop.width, crop.height)
  return { bytes: kept, png: crop.toDataURL('image/png'), width: crop.width, height: crop.height }
}

async function rows(browser, base) {
  mkdirSync(PAGES, { recursive: true })
  const manifest = {}
  const sizes = []
  for (const name of OK) {
    const context = await browser.newContext({ viewport: { width: 1280, height: 800 } })
    const page = await context.newPage()
    await page.goto(`${base}/app/#example=${name}`, { waitUntil: 'load' })
    await current(page)
    const made = await page.evaluate(rendered)
    if (typeof made === 'string') die(`${name} ${made}`)
    const path = join(PAGES, `${name}.png`)
    writeFileSync(path, Buffer.from(made.png.split(',')[1], 'base64'))
    manifest[name] = createHash('sha256').update(Buffer.from(made.bytes)).digest('hex')
    sizes.push(`${name} width="${Math.round(made.width * 4 / 9)}" height="${Math.round(made.height * 4 / 9)}"`)
    console.log(`wrote ${path}`)
    await context.close()
  }
  writeFileSync(join(PAGES, 'pages.json'), JSON.stringify(manifest, null, 2) + '\n')
  console.log(`wrote ${join(PAGES, 'pages.json')}`)
  for (const size of sizes) console.log(size)
}

/** Scroll every row's picture into view and wait until all of them have loaded. */
async function loaded(page) {
  const count = await page.$$eval('figure.shot img', (images) => images.length)
  for (let i = 0; i < count; i++) {
    const image = page.locator('figure.shot img').nth(i)
    await image.scrollIntoViewIfNeeded()
    await image.evaluate((img) => img.complete && img.naturalWidth > 0
      ? null
      : new Promise((done, fail) => {
          img.addEventListener('load', done, { once: true })
          img.addEventListener('error', () => fail(new Error(`${img.src} did not load`)), { once: true })
        }))
  }
  await page.evaluate(() => scrollTo(0, 0))
}

async function shots(base, engine) {
  mkdirSync(SHOTS, { recursive: true })
  const browser = await (engine === 'webkit' ? webkit : chromium).launch({ headless: true })
  const take = async ({ width, height, colorScheme, path, full = false, open = false }) => {
    const context = await browser.newContext({ viewport: { width, height }, colorScheme })
    const page = await context.newPage()
    await page.goto(`${base}/`, { waitUntil: 'networkidle' })
    await page.evaluate(() => document.fonts.ready)
    if (open) await page.$$eval('details', (all) => all.forEach((details) => (details.open = true)))
    if (full) await loaded(page)
    await page.screenshot({ path: join(SHOTS, path), fullPage: full })
    console.log(`wrote ${join(SHOTS, path)}`)
    await context.close()
  }
  for (const [width, height] of [[1280, 900], [390, 844]]) {
    for (const colorScheme of SCHEMES) {
      await take({ width, height, colorScheme, path: `landing-${engine}-${width}-${colorScheme}.png` })
    }
  }
  await take({ width: 1280, height: 900, colorScheme: 'light', full: true,
    path: `landing-${engine}-full-1280-light.png` })
  await take({ width: 390, height: 844, colorScheme: 'light', full: true,
    path: `landing-${engine}-full-390-light.png` })
  await take({ width: 1280, height: 900, colorScheme: 'dark', full: true, open: true,
    path: `landing-${engine}-full-1280-dark-open.png` })
  await browser.close()
}

/* -------------------------------------------------------------------- main */

if (argv.includes('--shots') && !argv.includes('--engine')) {
  assemble()
  for (const engine of ['chromium', 'webkit']) {
    const child = spawnSync('bun', [import.meta.path, '--shots', '--engine', engine], { stdio: 'inherit' })
    if (child.status !== 0) die(`the ${engine} child exited ${child.status}`)
  }
  process.exit(0)
}

if (OK.length !== 9) die(`web/index.html carries ${OK.length} ok examples, not 9`)
if (!argv.includes('--engine')) assemble()
const { url: base, server } = await serve(SITE)
if (argv.includes('--shots')) await shots(base, argv[argv.indexOf('--engine') + 1])
else {
  const browser = await chromium.launch({ headless: true })
  await capture(browser, base)
  await rows(browser, base)
  await browser.close()
}
server.close()
